--Table [DIM_PATIENT]
CREATE TABLE [DIM_PATIENT] (
	PATIENT_ID INT IDENTITY(1,1) PRIMARY KEY,
	AGE INT NOT NULL,
	GENDER NVARCHAR(255) NOT NULL,
    COUNTRY_NAME NVARCHAR(255) NOT NULL,
    SMOKING_STATUS NVARCHAR(255) NOT NULL,
    FAMILY_HISTORY NVARCHAR(255) NOT NULL,
    HYPERTENSION NVARCHAR(255) NOT NULL,
    ASTHMA NVARCHAR(255) NOT NULL,
    CIRRHOSIS NVARCHAR(255) NOT NULL,
    OTHER_CANCER NVARCHAR(255) NOT NULL,
    BMI_CATEGORY NVARCHAR(255) NOT NULL,
    CHOLESTEROL_CATEGORY NVARCHAR(255) NOT NULL
);
--( [bmi] < 18.5) ? "Underweight" : ( [bmi] >= 18.5 &&  < 25) ? "Normal" : ([bmi] >= 25 && [bmi] < 30) ? "Overweight" : ([bmi] >= 30) ? "Obese" : "Unknown"
--total rows of DIM_PATIENT: 890000
SELECT * FROM DIM_PATIENT;
TRUNCATE TABLE DIM_PATIENT;
DROP TABLE DIM_PATIENT;


--Table [DIM_CANCER_STAGE]
CREATE TABLE [DIM_CANCER_STAGE] (
    STAGE_ID INT IDENTITY(1,1) PRIMARY KEY,
    STAGE_NAME NVARCHAR(255) NOT NULL
);
--total rows of DIM_CANCER_STAGE: 890000
SELECT * FROM DIM_CANCER_STAGE;
TRUNCATE TABLE DIM_CANCER_STAGE;


--Table [DIM_TREAMENT]
CREATE TABLE [DIM_TREATMENT] (
    TREATMENT_ID INT IDENTITY(1,1) PRIMARY KEY,
    TREATMENT_TYPE NVARCHAR(255) NOT NULL
);
--total rows of DIM_TREATMENT: 890000
SELECT * FROM DIM_TREATMENT;
TRUNCATE TABLE DIM_TREATMENT;


--Table [DIM_DATE]
CREATE TABLE [DIM_DATE] (
    DATE_ID INT PRIMARY KEY,
    FULL_DATE DATE NOT NULL,
    DAY INT NOT NULL,
    MONTH INT NOT NULL,
    QUARTER INT NOT NULL,
    YEAR INT NOT NULL,
    DAY_OF_WEEK NVARCHAR(255),
    IS_WEEKEND CHAR(3) NOT NULL
);
--total rows of DIM_DATE: 6574 (2013 - 2030)
SELECT * FROM DIM_DATE;
TRUNCATE TABLE DIM_DATE;

DROP TABLE DIM_DATE;
SELECT * FROM DIM_DATE WHERE DATE_ID = 20160405


--Table [FACT_DIAGNOSIS]
CREATE TABLE [FACT_DIAGNOSIS] (
    FACT_DIAGNOSIS_ID INT IDENTITY(1,1) PRIMARY KEY,
    PATIENT_ID INT NOT NULL,
    DIAGNOSIS_DATE_ID INT NOT NULL,
    STAGE_ID INT NOT NULL,
    BMI DECIMAL(5,2) NOT NULL,
    CHOLESTEROL_LEVEL INT NOT NULL,
);
SELECT * FROM FACT_DIAGNOSIS;
TRUNCATE TABLE FACT_DIAGNOSIS;
DROP TABLE FACT_DIAGNOSIS;
--total rows of FACT_DIAGNOSIS: 890000
--Foreign key [FACT_DIAGNOSIS]
ALTER TABLE FACT_DIAGNOSIS ADD CONSTRAINT FACT_DIM_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES DIM_PATIENT(PATIENT_ID);
ALTER TABLE FACT_DIAGNOSIS ADD CONSTRAINT FACT_DIM_DATE FOREIGN KEY (DIAGNOSIS_DATE_ID) REFERENCES DIM_DATE(DATE_ID);
ALTER TABLE FACT_DIAGNOSIS ADD CONSTRAINT FACT_DIM_CANCER_STAGE FOREIGN KEY (STAGE_ID) REFERENCES DIM_CANCER_STAGE(STAGE_ID);



--Table [FACT_TREATMENT_OUTCOME]
CREATE TABLE [FACT_TREATMENT_OUTCOME] (
    FACT_TREATMENT_FACT_ID INT IDENTITY(1,1) PRIMARY KEY,
    PATIENT_ID INT NOT NULL,
    TREATMENT_ID INT NOT NULL,
    START_DATE_ID INT NOT NULL,
    END_DATE_ID INT NOT NULL,
    TREATMENT_DURATION_DAYS INT NOT NULL,
    IS_SURVIVED INT NOT NULL
);
SELECT * FROM FACT_TREATMENT_OUTCOME;
TRUNCATE TABLE FACT_TREATMENT_OUTCOME;
DROP TABLE FACT_TREATMENT_OUTCOME;
--total rows of FACT_TREATMENT_OUTCOME: 890000
--Foreign key [FACT_TREATMENT_OUTCOME]
ALTER TABLE FACT_TREATMENT_OUTCOME ADD CONSTRAINT FACTD_DIM_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES DIM_PATIENT(PATIENT_ID);
ALTER TABLE FACT_TREATMENT_OUTCOME ADD CONSTRAINT FACTD_DIM_TREATMENT FOREIGN KEY (TREATMENT_ID) REFERENCES DIM_TREATMENT(TREATMENT_ID);
ALTER TABLE FACT_TREATMENT_OUTCOME ADD CONSTRAINT FACTD_DIM_DATE_S FOREIGN KEY (START_DATE_ID) REFERENCES DIM_DATE(DATE_ID);
ALTER TABLE FACT_TREATMENT_OUTCOME ADD CONSTRAINT FACTD_DIM_DATE_E FOREIGN KEY (END_DATE_ID) REFERENCES DIM_DATE(DATE_ID);


TRUNCATE TABLE DIM_PATIENT;
TRUNCATE TABLE DIM_CANCER_STAGE;
TRUNCATE TABLE DIM_TREATMENT;
TRUNCATE TABLE DIM_DATE;
TRUNCATE TABLE FACT_DIAGNOSIS;
TRUNCATE TABLE FACT_TREATMENT_OUTCOME;

--Xóa khóa ngoại của DIM_TREATMENT và DIM_CANCER_STAGE
ALTER TABLE FACT_DIAGNOSIS DROP CONSTRAINT FACT_DIM_CANCER_STAGE;
ALTER TABLE FACT_DIAGNOSIS DROP CONSTRAINT FACT_DIM_PATIENT;
ALTER TABLE FACT_TREATMENT_OUTCOME DROP CONSTRAINT FACTD_DIM_TREATMENT;
ALTER TABLE FACT_TREATMENT_OUTCOME DROP CONSTRAINT FACTD_DIM_DATE_S;
ALTER TABLE FACT_TREATMENT_OUTCOME DROP CONSTRAINT FACTD_DIM_DATE_E;
ALTER TABLE FACT_TREATMENT_OUTCOME DROP CONSTRAINT FACTD_DIM_PATIENT;

select sum(IS_SURVIVED)
FROM FACT_TREATMENT_OUTCOME
WHERE 