--Table [DIM_PATIENT]
CREATE TABLE [DIM_PATIENT] (
	PATIENT_ID INT IDENTITY(1,1) PRIMARY KEY,
	AGE INT NOT NULL,
	GENDER NVARCHAR(255) NOT NULL,
	COUNTRY NVARCHAR(255) NOT NULL
);
--total rows of DIM_PATIENT: 890000
SELECT * FROM DIM_PATIENT;
TRUNCATE TABLE DIM_PATIENT;


--Table [DIM_LIFESTYLE]
CREATE TABLE [DIM_LIFESTYLE] (
	LIFESTYLE_ID INT IDENTITY(1,1) PRIMARY KEY,
	SMOKING_STATUS NVARCHAR(255) NOT NULL,
    BMI DECIMAL(5,2) NOT NULL,
    CHOLESTEROL_LEVEL INT NOT NULL,
    FAMILY_HISTORY NVARCHAR(255) NOT NULL;
);
--total rows of DIM_LIFESTYLE: 890000
SELECT * FROM DIM_LIFESTYLE;
TRUNCATE TABLE DIM_LIFESTYLE;


--Table [DIM_MEDICAL_HISTORY]
CREATE TABLE [DIM_MEDICAL_HISTORY] (
    MED_HISTORY_ID INT IDENTITY(1,1) PRIMARY KEY,
    HYPERTENSION NVARCHAR(255) NOT NULL,
    ASTHMA NVARCHAR(255) NOT NULL,
    CIRRHOSIS NVARCHAR(255) NOT NULL,
    OTHER_CANCER NVARCHAR(255) NOT NULL
);
--total rows of DIM_MEDICAL_HISTORY: 890000
SELECT * FROM DIM_MEDICAL_HISTORY;
TRUNCATE TABLE DIM_MEDICAL_HISTORY;


--Table [DIM_CANCER_STAGE]
CREATE TABLE [DIM_CANCER_STAGE] (
    STAGE_ID INT IDENTITY(1,1) PRIMARY KEY,
    STAGE_NAME NVARCHAR(255) NOT NULL
);
--total rows of DIM_CANCER_STAGE: 890000
SELECT * FROM DIM_CANCER_STAGE;
TRUNCATE TABLE DIM_CANCER_STAGE;


--Table [DIM_TREAMENT]
CREATE TABLE [DIM_TREATMENT] (
    TREATMENT_ID INT IDENTITY(1,1) PRIMARY KEY,
    TREATMENT_TYPE NVARCHAR(255) NOT NULL
);
--total rows of DIM_TREATMENT: 890000
SELECT * FROM DIM_TREATMENT;
TRUNCATE TABLE DIM_TREATMENT;


--Table [DIM_DATE]
CREATE TABLE [DIM_DATE] (
    DATE_ID INT IDENTITY(1,1) PRIMARY KEY,
    FULL_DATE DATE NOT NULL,
    DAY INT NOT NULL,
    MONTH INT NOT NULL,
    QUARTER INT NOT NULL,
    YEAR INT NOT NULL
);
--total rows of DIM_DATE: 890000
SELECT * FROM DIM_DATE;
TRUNCATE TABLE DIM_DATE;


--Table [FACT_DIAGNOSIS]
CREATE TABLE [FACT_DIAGNOSIS] (
    FACT_DIAGNOSIS_ID INT IDENTITY(1,1) PRIMARY KEY,
    PATIENT_ID INT NOT NULL,
    DIAGNOSIS_DATE_ID INT NOT NULL,
    STAGE_ID INT NOT NULL,
    LIFESTYLE_ID INT NOT NULL,
    MED_HISTORY_ID INT NOT NULL,
);
SELECT * FROM FACT_DIAGNOSIS;
TRUNCATE TABLE FACT_DIAGNOSIS;
DROP TABLE FACT_DIAGNOSIS;
--total rows of FACT_DIAGNOSIS: 890000
--Foreign key [FACT_DIAGNOSIS]
ALTER TABLE FACT_DIAGNOSIS ADD CONSTRAINT FACT_DIM_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES DIM_PATIENT(PATIENT_ID);
ALTER TABLE FACT_DIAGNOSIS ADD CONSTRAINT FACT_DIM_DATE FOREIGN KEY (DIAGNOSIS_DATE_ID) REFERENCES DIM_DATE(DATE_ID);
ALTER TABLE FACT_DIAGNOSIS ADD CONSTRAINT FACT_DIM_CANCER_STAGE FOREIGN KEY (STAGE_ID) REFERENCES DIM_CANCER_STAGE(STAGE_ID);
ALTER TABLE FACT_DIAGNOSIS ADD CONSTRAINT FACT_DIM_LIFESTYLE FOREIGN KEY (LIFESTYLE_ID) REFERENCES DIM_LIFESTYLE(LIFESTYLE_ID);
ALTER TABLE FACT_DIAGNOSIS ADD CONSTRAINT FACT_DIM_MED_HISTORY FOREIGN KEY (MED_HISTORY_ID) REFERENCES DIM_MEDICAL_HISTORY(MED_HISTORY_ID);



--Table [FACT_TREATMENT_OUTCOME]
CREATE TABLE [FACT_TREATMENT_OUTCOME] (
    FACT_TREATMENT_FACT_ID INT IDENTITY(1,1) PRIMARY KEY,
    PATIENT_ID INT NOT NULL,
    TREATMENT_ID INT NOT NULL,
    START_DATE_ID INT NOT NULL,
    SURVIVED NVARCHAR(3) NOT NULL,
    SURVIVAL_DAYS INT NOT NULL,
);
SELECT * FROM FACT_TREATMENT_OUTCOME;
TRUNCATE TABLE FACT_TREATMENT_OUTCOME;
DROP TABLE FACT_TREATMENT_OUTCOME;
--total rows of FACT_TREATMENT_OUTCOME: 890000
--Foreign key [FACT_TREATMENT_OUTCOME]
ALTER TABLE FACT_DIAGNOSIS ADD CONSTRAINT FACTD_DIM_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES DIM_PATIENT(PATIENT_ID);
ALTER TABLE FACT_DIAGNOSIS ADD CONSTRAINT FACTD_DIM_TREATMENT FOREIGN KEY (TREATMENT_ID) REFERENCES DIM_TREATMENT(TREATMENT_ID);
ALTER TABLE FACT_DIAGNOSIS ADD CONSTRAINT FACTD_DIM_DATE_S FOREIGN KEY (START_DATE_ID) REFERENCES DIM_DATE(DATE_ID);
ALTER TABLE FACT_DIAGNOSIS ADD CONSTRAINT FACTD_DIM_DATE_E FOREIGN KEY (END_DATE_ID) REFERENCES DIM_DATE(DATE_ID);


TRUNCATE TABLE DIM_PATIENT;
TRUNCATE TABLE DIM_LIFESTYLE;
TRUNCATE TABLE DIM_MEDICAL_HISTORY;
TRUNCATE TABLE DIM_CANCER_STAGE;
TRUNCATE TABLE DIM_TREATMENT;
TRUNCATE TABLE DIM_DATE;
TRUNCATE TABLE FACT_DIAGNOSIS;
TRUNCATE TABLE FACT_TREATMENT_OUTCOME;